### ISSUE TITLE
SER pathtrace sample does nothing, SER doesn't appear to work on Vulkan

### ISSUE THREAD

**Issue by BattleAxeVR** [nvpro-samples/vk_mini_samples#8] opened 2024-02-01 04:52 UTC
Just wanted to add this here as well for visibility, since the issue affects both Path Tracing SDK (in Vulkan mode, DX12 works fine), and this repo as well. 

Toggling the SER feature on/off has no effect on the framerate, nor the heatmap:

https://github.com/NVIDIAGameWorks/Path-Tracing-SDK/issues/2

I tried both game ready and latest beta drivers on my RTX 4090, in both code samples by Nvidia, and in both apps, the SER feature doesn't seem to work at all on Vulkan, only DX12 (in Path Tracing SDK). To enable it in that repo I had to add a couple lines, since it appears obviously that Vulkan is a second-class citizen compared to DX12.

**Comment by BattleAxeVR** [comment] 2024-02-01 04:55
@natduca can someone at Nvidia confirm whether this is broken or not? 

I'd like to implement SER in my VK path tracing engine but it has no effect in both of these samples and I think there may be a bug in the driver or something. I really need the perf and as SER is an advertised feature, and indeed the whole point of the ser_pathtrace sample here, the fact that it doesn't work is alarming.

These issues were reported nearly a year ago now and nothing's been done.

**Comment by BattleAxeVR** [comment] 2024-02-01 05:08
SER OFF:

![image](https://github.com/nvpro-samples/vk_mini_samples/assets/11604039/b58d5c58-c600-4f2a-81e8-d1840f871c0c)

**Comment by BattleAxeVR** [comment] 2024-02-01 05:08
SER ON:

![image](https://github.com/nvpro-samples/vk_mini_samples/assets/11604039/0f4d8e48-a0d0-409d-a40b-7f5e61b24c56)

**Comment by NBickford-NV** [comment] 2024-02-01 05:12
Looks like part of this is a silly bug in ser_pathtrace: the propagation of the specialization constant was accidentally removed 2 weeks ago in https://github.com/nvpro-samples/vk_mini_samples/commit/c5e5d6a550dd1ce96d6e1e62dfae2fdacdc51f9b#diff-6f12885eca6326d135a50a24e87c259021fad71cab5e5f23001e4f89020c78cbL557. (To reproduce, try modifying `payload.nrm` in the `USE_SER` branch of `traceRay()` in `pathtrace.rgen`.)

This fixes that:

```diff
    m_dutil->setObjectName(stages[eClosestHit].module, "Closest Hit");
#endif

+    stages[eRaygen].pSpecializationInfo = specialization.getSpecialization();
```

Could you try that on the 4090 and see if you see a difference now?

**Comment by BattleAxeVR** [comment] 2024-02-01 05:12
Now, the cube isn't a sea of red with SER OFF, like it's supposed to be, which leads me to believe...maybe SER is always-on?

But, that doesn't make sense either, because in the Path Tracing SDK, toggling it on/off makes a huge difference to the FPS on DX12 (nearly double) but nothing on VK. Just like here, the FPS is the exact same, as is the heat map.

I don't know what to think, but one thing's for sure, a sample should work, with the main feature toggled on/off showing a clear difference / benefit. If the sample's no longer valid, i.e. the SER feature is always enabled in the driver or newer Vulkan SDK maybe, that's something else. But I doubt that's the case because in the Path Tracing SDK, I get 12 FPS on VK and 22 on DX12 and that's no good. My engine only supports Vulkan so I can't simply switch to DX12 instead.

**Comment by BattleAxeVR** [comment] 2024-02-01 05:13
YES! That fixed it. Thanks so much!

**Comment by NBickford-NV** [comment] 2024-02-01 05:14
Awesome! I'll close this bug once the fix is in the public repo.

**Comment by BattleAxeVR** [comment] 2024-02-01 05:15
![image](https://github.com/nvpro-samples/vk_mini_samples/assets/11604039/c4e0d21c-23e0-416f-a434-c163db83be6f)

**Comment by BattleAxeVR** [comment] 2024-02-01 05:15
> Awesome! I'll close this bug once the fix is in the public repo.

Any chance you could help me figure out why it's also broken in the Path Tracing SDK? I'd like to validate VK + DX12 have the same exact perf w/ SER enabled.

**Comment by BattleAxeVR** [comment] 2024-02-01 05:16
I already got that repo to show the feature works / enumerated by adding it to the requested device extensions on VK, but the toggle isn't doing anything.

**Comment by mklefrancois** [comment] 2024-02-01 08:26
Thanks for reporting, this commit should fix the issue. 
https://github.com/nvpro-samples/vk_mini_samples/commit/6b70af33aad8bf3c214f77b72357e2350dd02b1c

**Closed as completed by mklefrancois** 2024-02-01 08:26 UTC

**Comment by NBickford-NV** [comment] 2024-02-02 00:53
@BattleAxeVR For the Path Tracing SDK, let's follow up on the issue at https://github.com/NVIDIAGameWorks/Path-Tracing-SDK/issues/2#issuecomment-1920882049 .
